version: '3.8'

services: 
  elasticsearch-server:
    image: elasticsearch
    container_name: elasticsearch-server
    restart: always
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment: 
      discovery.type: 'single-node'
    volumes: 
      - D:\ElasticSearch\data:/usr/share/elasticsearch/data
      # - /path/to/elasticsearch:/usr/share/elasticsearch/data