version: '3.8'

services: 
  elasticsearch-server:
    image: elasticsearch:7.10.1
    container_name: elasticsearch-server
    restart: always
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment: 
      discovery.type: 'single-node'
    volumes: 
      - ./data:/usr/share/elasticsearch/data